import type { Broker, EvidenceRecord, TariffVersion, TariffChange, MtfLot } from "@/types";

const KOTAK_EVIDENCE: EvidenceRecord[] = [
  {
    id: "ev-kn-mtf-int",
    broker: "kotak-neo",
    planId: "neo-trader",
    chargeName: "Annual MTF Interest Rate",
    sourceTitle: "Kotak Neo — Margin Trading Facility Rates (Demonstration)",
    sourceType: "official_pricing_page",
    sourceReference: "https://www.kotaksecurities.com/mtf (demonstration reference)",
    effectiveDate: "2026-01-01",
    lastCheckedDate: "2026-02-14",
    publishedValue: "14.99% p.a.",
    verificationStatus: "review_required",
    notes: "Demonstration data. Awaiting account-statement verification.",
  },
  {
    id: "ev-kn-mtf-brokerage",
    broker: "kotak-neo",
    planId: "neo-trader",
    chargeName: "MTF Brokerage",
    sourceTitle: "Kotak Neo — Charges (Demonstration)",
    sourceType: "official_pricing_page",
    sourceReference: "https://www.kotaksecurities.com/charges (demonstration reference)",
    effectiveDate: "2026-01-01",
    lastCheckedDate: "2026-02-14",
    publishedValue: "0.25% or ₹20 whichever is lower",
    verificationStatus: "review_required",
  },
  {
    id: "ev-kn-mtf-pledge",
    broker: "kotak-neo",
    planId: "neo-trader",
    chargeName: "Pledge Charge",
    sourceType: "help_article",
    sourceTitle: "Kotak Neo — Pledge FAQ (Demonstration)",
    sourceReference: "https://www.kotaksecurities.com/help/pledge (demonstration reference)",
    effectiveDate: "2026-01-01",
    lastCheckedDate: "2026-02-14",
    publishedValue: "₹20 + GST per pledge request",
    verificationStatus: "review_required",
  },
  {
    id: "ev-kn-mtf-unpledge",
    broker: "kotak-neo",
    planId: "neo-trader",
    chargeName: "Unpledge Charge",
    sourceType: "help_article",
    sourceTitle: "Kotak Neo — Unpledge FAQ (Demonstration)",
    sourceReference: "https://www.kotaksecurities.com/help/unpledge (demonstration reference)",
    effectiveDate: "2026-01-01",
    lastCheckedDate: "2026-02-14",
    publishedValue: "₹20 + GST per unpledge request",
    verificationStatus: "review_required",
  },
  {
    id: "ev-kn-mtf-dp",
    broker: "kotak-neo",
    planId: "neo-trader",
    chargeName: "DP Charges (Sell)",
    sourceType: "official_pricing_page",
    sourceTitle: "Kotak Neo — DP charges (Demonstration)",
    sourceReference: "https://www.kotaksecurities.com/dp (demonstration reference)",
    effectiveDate: "2026-01-01",
    lastCheckedDate: "2026-02-14",
    publishedValue: "₹15.93 per scrip per day (incl. GST)",
    verificationStatus: "review_required",
  },
];

const KOTAK_NEO: Broker = {
  slug: "kotak-neo",
  name: "Kotak Neo",
  legalName: "Kotak Securities Limited",
  established: 1994,
  headquarters: "Mumbai, India",
  sebiRegNo: "INZ000200137",
  overview:
    "Kotak Neo is the digital brokerage arm of Kotak Securities. This profile presents Margin Trading Facility (MTF) tariffs modelled from publicly available information for demonstration only. Every value is marked Review Required until verified against an account statement.",
  supportedProducts: ["MTF"],
  currentTariffVersion: "v2026.02",
  lastVerificationDate: "2026-02-14",
  verificationStatus: "review_required",
  plans: [
    {
      id: "neo-trader",
      name: "Neo Trader",
      description: "Standard Kotak Neo plan used for demonstration.",
      isDefault: true,
      buyBrokerage: {
        chargeKey: "buy_brokerage",
        value: 0.25,
        unit: "percent",
        max: 20,
        gstApplicable: true,
        verificationStatus: "review_required",
        notes: "0.25% of buy turnover, capped at ₹20 per order.",
      },
      sellBrokerage: {
        chargeKey: "sell_brokerage",
        value: 0.25,
        unit: "percent",
        max: 20,
        gstApplicable: true,
        verificationStatus: "review_required",
        notes: "0.25% of sell turnover, capped at ₹20 per order.",
      },
    },
  ],
  mtf: {
    annualInterestRatePct: 14.99,
    minMarginPct: 25,
    brokerFundedPct: 75,
    pledgeFeeFlat: 20,
    unpledgeFeeFlat: 20,
    dpChargeFlat: 15.93,
    gstOnCharges: 18,
    stt: { buy: 0.1, sell: 0.1 },
    stampDuty: 0.015,
    exchangeTxnPct: 0.00297,
    sebiChargesPct: 0.0001,
    ipftPct: 0.0001,
  },
  evidenceIds: KOTAK_EVIDENCE.map((e) => e.id),
  disclaimer:
    "KnowYourPNL is not affiliated with Kotak Securities. All logos and names remain the property of their respective owners. All values shown here are demonstration data and must be verified against your own account statement before use.",
};

const TARIFF_VERSIONS: TariffVersion[] = [
  {
    id: "kn-neo-v2026.02",
    brokerSlug: "kotak-neo",
    planId: "neo-trader",
    version: "v2026.02",
    effectiveDate: "2026-01-01",
    publishedDate: "2025-12-20",
    supersedes: "kn-neo-v2025.09",
    changeSummary: "Demonstration: DP charges rounding refined; interest rate held at 14.99%.",
    verificationStatus: "review_required",
    lastCheckedDate: "2026-02-14",
  },
  {
    id: "kn-neo-v2025.09",
    brokerSlug: "kotak-neo",
    planId: "neo-trader",
    version: "v2025.09",
    effectiveDate: "2025-09-01",
    publishedDate: "2025-08-18",
    supersedes: "kn-neo-v2025.04",
    changeSummary: "Demonstration: pledge fee moved from tiered to flat ₹20.",
    verificationStatus: "estimated",
    lastCheckedDate: "2025-10-02",
  },
  {
    id: "kn-neo-v2025.04",
    brokerSlug: "kotak-neo",
    planId: "neo-trader",
    version: "v2025.04",
    effectiveDate: "2025-04-01",
    publishedDate: "2025-03-15",
    changeSummary: "Baseline reconstructed from public pricing snapshots (demonstration).",
    verificationStatus: "estimated",
    lastCheckedDate: "2025-06-10",
  },
];

export const TARIFF_CHANGES: Record<string, TariffChange[]> = {
  "kn-neo-v2026.02": [
    { chargeKey: "dp_charge", previousValue: "₹15.34", newValue: "₹15.93", note: "GST rounding aligned." },
  ],
  "kn-neo-v2025.09": [
    { chargeKey: "pledge_fee", previousValue: "Tiered ₹15–₹25", newValue: "Flat ₹20", note: "Standardised." },
    { chargeKey: "unpledge_fee", previousValue: "Tiered ₹15–₹25", newValue: "Flat ₹20" },
  ],
  "kn-neo-v2025.04": [{ chargeKey: "baseline", newValue: "Initial demonstration snapshot" }],
};

const seedLedger: MtfLot[] = [
  {
    id: "lot-demo-1",
    brokerSlug: "kotak-neo",
    planId: "neo-trader",
    instrument: "RELIANCE",
    purchaseDate: "2026-01-08",
    quantity: 40,
    buyPrice: 2890.5,
    currentPrice: 3012.75,
    userCapital: 28905,
    brokerFunded: 86715,
    mtfInterest: 1408,
    entryCharges: 152,
    estimatedExitCharges: 168,
    breakevenPrice: 2933.9,
    unrealisedPnl: 4890,
    estimatedNetPnl: 3162,
    tariffVersion: "v2026.02",
    methodologyVersion: "mtf-methodology-v1",
    verificationStatus: "review_required",
    isMock: true,
    createdAt: "2026-01-08T10:12:00Z",
  },
  {
    id: "lot-demo-2",
    brokerSlug: "kotak-neo",
    planId: "neo-trader",
    instrument: "HDFCBANK",
    purchaseDate: "2026-01-22",
    quantity: 30,
    buyPrice: 1682.1,
    currentPrice: 1712.6,
    userCapital: 12615.75,
    brokerFunded: 37847.25,
    mtfInterest: 388,
    entryCharges: 84,
    estimatedExitCharges: 96,
    breakevenPrice: 1701.53,
    unrealisedPnl: 915,
    estimatedNetPnl: 347,
    tariffVersion: "v2026.02",
    methodologyVersion: "mtf-methodology-v1",
    verificationStatus: "review_required",
    isMock: true,
    createdAt: "2026-01-22T09:47:00Z",
  },
  {
    id: "lot-demo-3",
    brokerSlug: "kotak-neo",
    planId: "neo-trader",
    instrument: "INFY",
    purchaseDate: "2025-12-15",
    quantity: 60,
    buyPrice: 1548.9,
    currentPrice: 1502.4,
    userCapital: 23233.5,
    brokerFunded: 69700.5,
    mtfInterest: 1834,
    entryCharges: 138,
    estimatedExitCharges: 148,
    breakevenPrice: 1584.23,
    unrealisedPnl: -2790,
    estimatedNetPnl: -4910,
    tariffVersion: "v2026.02",
    methodologyVersion: "mtf-methodology-v1",
    verificationStatus: "review_required",
    isMock: true,
    createdAt: "2025-12-15T11:03:00Z",
  },
];

export const MOCK = {
  brokers: [KOTAK_NEO] as Broker[],
  evidence: KOTAK_EVIDENCE,
  tariffVersions: TARIFF_VERSIONS,
  seedLedger,
  methodologyVersion: "mtf-methodology-v1",
};
